# Creating Arrays

In [2]:
import numpy as np

## `np.zeros`

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((3,4))  # you pass a tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Some vocabulary

- **axis:** each dimension of the array
- **rank:** number of axis. *e.g.* 3x4 is rank 2
- **shape:** axis length. *e.g.* 3x4 is shape (3,4)
- **size:** total number of elements *e.g.* 3x4 size is 12

In [5]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
a.shape

(3, 4)

In [7]:
a.ndim  # len(a.shape)

2

In [8]:
a.size

12

## N-dimensional arrays

In [9]:
np.zeros((2,3,4))  # can create array of any rank

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Array type

In [10]:
type(np.zeros((3,4)))  # ndarray

numpy.ndarray

## `np.ones`

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## `np.full`

In [12]:
np.full((3,4), np.pi)  # should it be fill

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

## `np.empty`

In [13]:
np.empty((2,3))  # whatever in the memory

array([[4.65134073e-310, 0.00000000e+000, 2.41907520e-312],
       [2.44029516e-312, 1.12465777e-312, 2.02566915e-322]])

## `np.array`

In [14]:
np.array([[1,2,3,4], [10,20,30,40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

## `np.arange`

In [15]:
np.arange(1,5)  # not including second number, like python range

array([1, 2, 3, 4])

In [16]:
np.arange(1., 5.)  # works with foats

array([1., 2., 3., 4.])

In [17]:
np.arange(1, 5, 0.5)  # step

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

## `np.fromfunction`

In [18]:
def my_function(z, y, x):
    return x + 10 * y + 100 * z

np.fromfunction(my_function, (3, 2, 10))

array([[[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [ 10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.]],

       [[100., 101., 102., 103., 104., 105., 106., 107., 108., 109.],
        [110., 111., 112., 113., 114., 115., 116., 117., 118., 119.]],

       [[200., 201., 202., 203., 204., 205., 206., 207., 208., 209.],
        [210., 211., 212., 213., 214., 215., 216., 217., 218., 219.]]])

# Array data

## `dtype`

In [19]:
c = np.arange(1,5)
print(c.dtype, c)

int64 [1 2 3 4]


In [20]:
z = np.zeros(5)
print(z.dtype, z)

float64 [0. 0. 0. 0. 0.]


In [21]:
d = np.arange(1,5, dtype=np.complex64)
print(d.dtype, d)

complex64 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [22]:
# types are: signed [int8, int16, int32, int64], usigned [uint8 | 16 | 32 | 64]
# float [float16 | 32 | 64], complex [complex64 | 128]

# Reshaping an array

## In place

In [23]:
g = np.arange(24)
print(g)
print("Rank:", g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Rank: 1


In [24]:
g.shape = (6,4)
print(g)
print("Rank:", g.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Rank: 2


In [25]:
g.shape = (2, 3, 4)
print(g)
print("Rank:", g.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Rank: 3


## `reshape`
return new `ndarray` pointing at the same data. this means that modifying one array will change the other

In [26]:
g2 = g.reshape(4, 6)
print(g2)
print("Rank:", g2.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Rank: 2


In [27]:
g2[1,2] = 999
g2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7, 999,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

In [28]:
g

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [999,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

## `ravel`

In [29]:
g.ravel()  # return 1d array that points at the same data

array([  0,   1,   2,   3,   4,   5,   6,   7, 999,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

# Arithmetic operations

In [30]:
a = np.array([14, 23, 32, 41])
b = np.array([5, 4, 3, 2])
print("a + b = ", a + b)
print("a - b = ", a - b)
print("a * b = ", a * b)  # not matrix multiplication
print("a / b = ", a / b)
print("a // b = ", a // b)
print("a % b = ", a % b)
print("a ** b = ", a ** b)

a + b =  [19 27 35 43]
a - b =  [ 9 19 29 39]
a * b =  [70 92 96 82]
a / b =  [ 2.8         5.75       10.66666667 20.5       ]
a // b =  [ 2  5 10 20]
a % b =  [4 3 2 1]
a ** b =  [537824 279841  32768   1681]


# Broadcasting

## First rule

In [31]:
h = np.arange(5).reshape(1, 1, 5)
h

array([[[0, 1, 2, 3, 4]]])

In [32]:
h + [10, 20, 30, 40, 50]  # same as: h + [[[10, 20, 30, 40, 50]]]

array([[[10, 21, 32, 43, 54]]])

## Second rule

In [33]:
k = np.arange(6).reshape(2, 3)
k

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
k + [[100], [200]]  # same as: k + [[100, 100, 100], [200, 200, 200]]

array([[100, 101, 102],
       [203, 204, 205]])

In [35]:
# combine rule 1 & 2
k + [100, 200, 300]
# after rule 1: [[100, 200, 300]]
# after rule 2: [[100, 200, 300], [100, 200, 300]]

array([[100, 201, 302],
       [103, 204, 305]])

In [36]:
k + 1000
# [[1000]]  k: 2,3  1000: 2,1
# [[1000, 1000, 1000], [1000, 1000, 1000]]

array([[1000, 1001, 1002],
       [1003, 1004, 1005]])

## Third rule

In [37]:
# after rules 1 & 2, the sizes of all arrays must match
try:
    k + [33, 44]
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (2,3) (2,) 


## Upcasting

In [38]:
k1 = np.arange(0, 5, dtype=np.uint8)
print(k1.dtype, k1)

uint8 [0 1 2 3 4]


In [39]:
k2 = k1 + np.array([5, 6, 7, 8, 9], dtype=np.int8)
print(k2.dtype, k2)
# upcasted to in16 to represent both int and uint 8

int16 [ 5  7  9 11 13]


In [40]:
k3 = k1 + 1.5
print(k3.dtype, k3)
# upcasted to float

float64 [1.5 2.5 3.5 4.5 5.5]


# Conditional operators

In [41]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False])

In [42]:
m < 25  # broadcasting

array([ True,  True, False, False])

In [43]:
m[m < 25]  # filter

array([20, -5])

# Mathematical and statistical functions

## `ndarray` methods

In [44]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print(a)
print("mean =", a.mean())

[[-2.5  3.1  7. ]
 [10.  11.  12. ]]
mean = 6.766666666666667


In [45]:
for func in (a.min, a.max, a.sum, a.prod, a.std, a.var):
    print(func.__name__, "=", func())

min = -2.5
max = 12.0
sum = 40.6
prod = -71610.0
std = 5.084835843520964
var = 25.855555555555554


In [46]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [47]:
c.sum(axis=0)  # sum across matrices

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [48]:
c.sum(axis=1)  # sum across rows

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [49]:
c.sum(axis=(0,2))  # sum across matrices and columns

array([ 60,  92, 124])

In [50]:
0+1+2+3 + 12+13+14+15, 4+5+6+7 + 16+17+18+19, 8+9+10+11 + 20+21+22+23

(60, 92, 124)

## Universal functions (ufunc)

In [51]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
np.square(a)

array([[  6.25,   9.61,  49.  ],
       [100.  , 121.  , 144.  ]])

In [52]:
print("Original ndarray")
print(a)
for func in (np.abs, np.sqrt, np.exp, np.log, np.sign, np.ceil, np.modf, np.isnan, np.cos):
    print("\n", func.__name__)
    print(func(a))

Original ndarray
[[-2.5  3.1  7. ]
 [10.  11.  12. ]]

 absolute
[[ 2.5  3.1  7. ]
 [10.  11.  12. ]]

 sqrt
[[       nan 1.76068169 2.64575131]
 [3.16227766 3.31662479 3.46410162]]

 exp
[[8.20849986e-02 2.21979513e+01 1.09663316e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05]]

 log
[[       nan 1.13140211 1.94591015]
 [2.30258509 2.39789527 2.48490665]]

 sign
[[-1.  1.  1.]
 [ 1.  1.  1.]]

 ceil
[[-2.  4.  7.]
 [10. 11. 12.]]

 modf
(array([[-0.5,  0.1,  0. ],
       [ 0. ,  0. ,  0. ]]), array([[-2.,  3.,  7.],
       [10., 11., 12.]]))

 isnan
[[False False False]
 [False False False]]

 cos
[[-0.80114362 -0.99913515  0.75390225]
 [-0.83907153  0.0044257   0.84385396]]


/tmp/ipykernel_5799/2634842825.py:5: RuntimeWarning: invalid value encountered in sqrt
  print(func(a))
/tmp/ipykernel_5799/2634842825.py:5: RuntimeWarning: invalid value encountered in log
  print(func(a))


## Binary ufuncs

In [53]:
a = np.array([1, -2, 3, 4])
b = np.array([2, 8, -1, 7])
np.add(a, b)  # a + b

array([ 3,  6,  2, 11])

In [54]:
np.greater(a, b)  # a > b

array([False, False,  True, False])

In [55]:
np.maximum(a, b)

array([2, 8, 3, 7])

In [56]:
np.copysign(a, b)  # copy the sign of the second array

array([ 1.,  2., -3.,  4.])

# Array indexing

In [57]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
a[3]

np.int64(19)

In [58]:
a[2:5]

array([ 3, 19, 13])

In [59]:
a[2:-1]

array([ 3, 19, 13,  7])

In [60]:
a[:2]

array([1, 5])

In [61]:
a[2::2]

array([ 3, 13,  3])

In [62]:
a[::-1]

array([ 3,  7, 13, 19,  3,  5,  1])

In [63]:
a[3] = 999
a

array([  1,   5,   3, 999,  13,   7,   3])

In [64]:
a[2:5] = [997, 998, 999]
a

array([  1,   5, 997, 998, 999,   7,   3])

## Differences with regular python arrays

In [65]:
a [2:5] = -1  # broadcasting
a

array([ 1,  5, -1, -1, -1,  7,  3])

In [66]:
try:
    a[2:5] = [1, 2, 3, 4, 5, 6]  # too long
except ValueError as e:
    print(e)

could not broadcast input array from shape (6,) into shape (3,)


In [67]:
try:
    del a[2:5]
except ValueError as e:
    print(e)

cannot delete array elements


In [68]:
# points at the same data buffer
a_slice = a[2:6]
a_slice[1] = 1000
a 

array([   1,    5,   -1, 1000,   -1,    7,    3])

In [69]:
a[3] = 2000
a_slice

array([  -1, 2000,   -1,    7])

In [70]:
another_slice = a[2:6].copy()
another_slice[1] = 3000
a  # didn't change

array([   1,    5,   -1, 2000,   -1,    7,    3])

In [71]:
a[3] = 4000
another_slice  # didn't change

array([  -1, 3000,   -1,    7])

## Multidimensional arrays

In [72]:
b = np.arange(48).reshape(4, 12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [73]:
b[1, 2]  # row 1, col 2

np.int64(14)

In [74]:
b[1, :]  # row 1, all cols

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [75]:
b[:, 1]  # all rows, col 1

array([ 1, 13, 25, 37])

In [76]:
b[1:3, :] 

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

## Fancy indexing

In [77]:
b[(0,2), 2:5]  # rows 0 and 2, cols 2 to 4 

array([[ 2,  3,  4],
       [26, 27, 28]])

In [78]:
b[:, (-1, 2, -1)]

array([[11,  2, 11],
       [23, 14, 23],
       [35, 26, 35],
       [47, 38, 47]])

In [79]:
b[(-1, 2, -1, 2), (5, 9, 1, 9)]

array([41, 33, 37, 33])

## Higher dimensions

In [81]:
c = b.reshape(4, 2, 6)
c

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [82]:
c[2, 1, 4]

np.int64(34)

In [83]:
c[2, :, 3]

array([27, 33])

## Ellipsis `...`

In [84]:
c[2, ...]  # matrix 2, all rows, all cosl. => c[2, :, :]

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [86]:
c[2, 1, ...]  # c[2, 1, :]

array([30, 31, 32, 33, 34, 35])