# Creating Arrays

In [2]:
import numpy as np

## `np.zeros`

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((3,4))  # you pass a tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Some vocabulary

- **axis:** each dimension of the array
- **rank:** number of axis. *e.g.* 3x4 is rank 2
- **shape:** axis length. *e.g.* 3x4 is shape (3,4)
- **size:** total number of elements *e.g.* 3x4 size is 12

In [5]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
a.shape

(3, 4)

In [7]:
a.ndim  # len(a.shape)

2

In [8]:
a.size

12

## N-dimensional arrays

In [9]:
np.zeros((2,3,4))  # can create array of any rank

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Array type

In [10]:
type(np.zeros((3,4)))  # ndarray

numpy.ndarray

## `np.ones`

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## `np.full`

In [12]:
np.full((3,4), np.pi)  # should it be fill

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

## `np.empty`

In [13]:
np.empty((2,3))  # whatever in the memory

array([[4.64251799e-310, 0.00000000e+000, 6.89995908e-310],
       [6.89999938e-310, 6.89999773e-310, 6.90001142e-310]])

## `np.array`

In [14]:
np.array([[1,2,3,4], [10,20,30,40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

## `np.arange`

In [15]:
np.arange(1,5)  # not including second number, like python range

array([1, 2, 3, 4])

In [16]:
np.arange(1., 5.)  # works with foats

array([1., 2., 3., 4.])

In [17]:
np.arange(1, 5, 0.5)  # step

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

## `np.fromfunction`

In [18]:
def my_function(z, y, x):
    return x + 10 * y + 100 * z

np.fromfunction(my_function, (3, 2, 10))

array([[[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [ 10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.]],

       [[100., 101., 102., 103., 104., 105., 106., 107., 108., 109.],
        [110., 111., 112., 113., 114., 115., 116., 117., 118., 119.]],

       [[200., 201., 202., 203., 204., 205., 206., 207., 208., 209.],
        [210., 211., 212., 213., 214., 215., 216., 217., 218., 219.]]])

# Array data

## `dtype`

In [19]:
c = np.arange(1,5)
print(c.dtype, c)

int64 [1 2 3 4]


In [22]:
z = np.zeros(5)
print(z.dtype, z)

float64 [0. 0. 0. 0. 0.]


In [23]:
d = np.arange(1,5, dtype=np.complex64)
print(d.dtype, d)

complex64 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [25]:
# types are: signed [int8, int16, int32, int64], usigned [uint8 | 16 | 32 | 64]
# float [float16 | 32 | 64], complex [complex64 | 128]

# Reshaping an array

## In place

In [27]:
g = np.arange(24)
print(g)
print("Rank:", g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Rank: 1


In [28]:
g.shape = (6,4)
print(g)
print("Rank:", g.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Rank: 2


In [29]:
g.shape = (2, 3, 4)
print(g)
print("Rank:", g.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Rank: 3


## `reshape`
return new `ndarray` pointing at the same data. this means that modifying one array will change the other