# Creating Arrays

In [2]:
import numpy as np

## `np.zeros`

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((3,4))  # you pass a tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Some vocabulary

- **axis:** each dimension of the array
- **rank:** number of axis. *e.g.* 3x4 is rank 2
- **shape:** axis length. *e.g.* 3x4 is shape (3,4)
- **size:** total number of elements *e.g.* 3x4 size is 12

In [5]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
a.shape

(3, 4)

In [7]:
a.ndim  # len(a.shape)

2

In [8]:
a.size

12

## N-dimensional arrays

In [9]:
np.zeros((2,3,4))  # can create array of any rank

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Array type

In [10]:
type(np.zeros((3,4)))  # ndarray

numpy.ndarray

## `np.ones`

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## `np.full`

In [12]:
np.full((3,4), np.pi)  # should it be fill

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

## `np.empty`

In [13]:
np.empty((2,3))  # whatever in the memory

array([[4.64103359e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

## `np.array`

In [14]:
np.array([[1,2,3,4], [10,20,30,40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

## `np.arange`

In [15]:
np.arange(1,5)  # not including second number, like python range

array([1, 2, 3, 4])

In [16]:
np.arange(1., 5.)  # works with foats

array([1., 2., 3., 4.])

In [17]:
np.arange(1, 5, 0.5)  # step

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

## `np.fromfunction`

In [18]:
def my_function(z, y, x):
    return x + 10 * y + 100 * z

np.fromfunction(my_function, (3, 2, 10))

array([[[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [ 10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.]],

       [[100., 101., 102., 103., 104., 105., 106., 107., 108., 109.],
        [110., 111., 112., 113., 114., 115., 116., 117., 118., 119.]],

       [[200., 201., 202., 203., 204., 205., 206., 207., 208., 209.],
        [210., 211., 212., 213., 214., 215., 216., 217., 218., 219.]]])

# Array data

## `dtype`

In [19]:
c = np.arange(1,5)
print(c.dtype, c)

int64 [1 2 3 4]


In [20]:
z = np.zeros(5)
print(z.dtype, z)

float64 [0. 0. 0. 0. 0.]


In [21]:
d = np.arange(1,5, dtype=np.complex64)
print(d.dtype, d)

complex64 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [22]:
# types are: signed [int8, int16, int32, int64], usigned [uint8 | 16 | 32 | 64]
# float [float16 | 32 | 64], complex [complex64 | 128]

# Reshaping an array

## In place

In [23]:
g = np.arange(24)
print(g)
print("Rank:", g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Rank: 1


In [24]:
g.shape = (6,4)
print(g)
print("Rank:", g.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Rank: 2


In [25]:
g.shape = (2, 3, 4)
print(g)
print("Rank:", g.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Rank: 3


## `reshape`
return new `ndarray` pointing at the same data. this means that modifying one array will change the other

In [26]:
g2 = g.reshape(4, 6)
print(g2)
print("Rank:", g2.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Rank: 2


In [27]:
g2[1,2] = 999
g2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7, 999,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

In [28]:
g

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [999,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

## `ravel`

In [29]:
g.ravel()  # return 1d array that points at the same data

array([  0,   1,   2,   3,   4,   5,   6,   7, 999,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

# Arithmetic operations

In [30]:
a = np.array([14, 23, 32, 41])
b = np.array([5, 4, 3, 2])
print("a + b = ", a + b)
print("a - b = ", a - b)
print("a * b = ", a * b)  # not matrix multiplication
print("a / b = ", a / b)
print("a // b = ", a // b)
print("a % b = ", a % b)
print("a ** b = ", a ** b)

a + b =  [19 27 35 43]
a - b =  [ 9 19 29 39]
a * b =  [70 92 96 82]
a / b =  [ 2.8         5.75       10.66666667 20.5       ]
a // b =  [ 2  5 10 20]
a % b =  [4 3 2 1]
a ** b =  [537824 279841  32768   1681]


# Broadcasting

## First rule

In [31]:
h = np.arange(5).reshape(1, 1, 5)
h

array([[[0, 1, 2, 3, 4]]])

In [32]:
h + [10, 20, 30, 40, 50]  # same as: h + [[[10, 20, 30, 40, 50]]]

array([[[10, 21, 32, 43, 54]]])

## Second rule

In [33]:
k = np.arange(6).reshape(2, 3)
k

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
k + [[100], [200]]  # same as: k + [[100, 100, 100], [200, 200, 200]]

array([[100, 101, 102],
       [203, 204, 205]])

In [35]:
# combine rule 1 & 2
k + [100, 200, 300]
# after rule 1: [[100, 200, 300]]
# after rule 2: [[100, 200, 300], [100, 200, 300]]

array([[100, 201, 302],
       [103, 204, 305]])

In [36]:
k + 1000
# [[1000]]  k: 2,3  1000: 2,1
# [[1000, 1000, 1000], [1000, 1000, 1000]]

array([[1000, 1001, 1002],
       [1003, 1004, 1005]])

## Third rule

In [37]:
# after rules 1 & 2, the sizes of all arrays must match
try:
    k + [33, 44]
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (2,3) (2,) 


## Upcasting

In [38]:
k1 = np.arange(0, 5, dtype=np.uint8)
print(k1.dtype, k1)

uint8 [0 1 2 3 4]


In [39]:
k2 = k1 + np.array([5, 6, 7, 8, 9], dtype=np.int8)
print(k2.dtype, k2)
# upcasted to in16 to represent both int and uint 8

int16 [ 5  7  9 11 13]


In [40]:
k3 = k1 + 1.5
print(k3.dtype, k3)
# upcasted to float

float64 [1.5 2.5 3.5 4.5 5.5]


# Conditional operators

In [41]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False])

In [42]:
m < 25  # broadcasting

array([ True,  True, False, False])

In [43]:
m[m < 25]  # filter

array([20, -5])

# Mathematical and statistical functions

## `ndarray` methods

In [44]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print(a)
print("mean =", a.mean())

[[-2.5  3.1  7. ]
 [10.  11.  12. ]]
mean = 6.766666666666667


In [45]:
for func in (a.min, a.max, a.sum, a.prod, a.std, a.var):
    print(func.__name__, "=", func())

min = -2.5
max = 12.0
sum = 40.6
prod = -71610.0
std = 5.084835843520964
var = 25.855555555555554


In [46]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [47]:
c.sum(axis=0)  # sum across matrices

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [48]:
c.sum(axis=1)  # sum across rows

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [49]:
c.sum(axis=(0,2))  # sum across matrices and columns

array([ 60,  92, 124])

In [50]:
0+1+2+3 + 12+13+14+15, 4+5+6+7 + 16+17+18+19, 8+9+10+11 + 20+21+22+23

(60, 92, 124)

## Universal functions (ufunc)

In [51]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
np.square(a)

array([[  6.25,   9.61,  49.  ],
       [100.  , 121.  , 144.  ]])

In [52]:
print("Original ndarray")
print(a)
for func in (np.abs, np.sqrt, np.exp, np.log, np.sign, np.ceil, np.modf, np.isnan, np.cos):
    print("\n", func.__name__)
    print(func(a))

Original ndarray
[[-2.5  3.1  7. ]
 [10.  11.  12. ]]

 absolute
[[ 2.5  3.1  7. ]
 [10.  11.  12. ]]

 sqrt
[[       nan 1.76068169 2.64575131]
 [3.16227766 3.31662479 3.46410162]]

 exp
[[8.20849986e-02 2.21979513e+01 1.09663316e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05]]

 log
[[       nan 1.13140211 1.94591015]
 [2.30258509 2.39789527 2.48490665]]

 sign
[[-1.  1.  1.]
 [ 1.  1.  1.]]

 ceil
[[-2.  4.  7.]
 [10. 11. 12.]]

 modf
(array([[-0.5,  0.1,  0. ],
       [ 0. ,  0. ,  0. ]]), array([[-2.,  3.,  7.],
       [10., 11., 12.]]))

 isnan
[[False False False]
 [False False False]]

 cos
[[-0.80114362 -0.99913515  0.75390225]
 [-0.83907153  0.0044257   0.84385396]]


/tmp/ipykernel_10437/2634842825.py:5: RuntimeWarning: invalid value encountered in sqrt
  print(func(a))
/tmp/ipykernel_10437/2634842825.py:5: RuntimeWarning: invalid value encountered in log
  print(func(a))


## Binary ufuncs

In [53]:
a = np.array([1, -2, 3, 4])
b = np.array([2, 8, -1, 7])
np.add(a, b)  # a + b

array([ 3,  6,  2, 11])

In [54]:
np.greater(a, b)  # a > b

array([False, False,  True, False])

In [55]:
np.maximum(a, b)

array([2, 8, 3, 7])

In [56]:
np.copysign(a, b)  # copy the sign of the second array

array([ 1.,  2., -3.,  4.])

# Array indexing

In [57]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
a[3]

np.int64(19)

In [58]:
a[2:5]

array([ 3, 19, 13])

In [59]:
a[2:-1]

array([ 3, 19, 13,  7])

In [60]:
a[:2]

array([1, 5])

In [61]:
a[2::2]

array([ 3, 13,  3])

In [62]:
a[::-1]

array([ 3,  7, 13, 19,  3,  5,  1])

In [63]:
a[3] = 999
a

array([  1,   5,   3, 999,  13,   7,   3])

In [64]:
a[2:5] = [997, 998, 999]
a

array([  1,   5, 997, 998, 999,   7,   3])

## Differences with regular python arrays

In [65]:
a [2:5] = -1  # broadcasting
a

array([ 1,  5, -1, -1, -1,  7,  3])

In [66]:
try:
    a[2:5] = [1, 2, 3, 4, 5, 6]  # too long
except ValueError as e:
    print(e)

could not broadcast input array from shape (6,) into shape (3,)


In [67]:
try:
    del a[2:5]
except ValueError as e:
    print(e)

cannot delete array elements


In [68]:
# points at the same data buffer
a_slice = a[2:6]
a_slice[1] = 1000
a 

array([   1,    5,   -1, 1000,   -1,    7,    3])

In [69]:
a[3] = 2000
a_slice

array([  -1, 2000,   -1,    7])

In [70]:
another_slice = a[2:6].copy()
another_slice[1] = 3000
a  # didn't change

array([   1,    5,   -1, 2000,   -1,    7,    3])

In [71]:
a[3] = 4000
another_slice  # didn't change

array([  -1, 3000,   -1,    7])

## Multidimensional arrays

In [72]:
b = np.arange(48).reshape(4, 12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [73]:
b[1, 2]  # row 1, col 2

np.int64(14)

In [74]:
b[1, :]  # row 1, all cols

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [75]:
b[:, 1]  # all rows, col 1

array([ 1, 13, 25, 37])

In [76]:
b[1:3, :] 

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

## Fancy indexing

In [77]:
b[(0,2), 2:5]  # rows 0 and 2, cols 2 to 4 

array([[ 2,  3,  4],
       [26, 27, 28]])

In [78]:
b[:, (-1, 2, -1)]

array([[11,  2, 11],
       [23, 14, 23],
       [35, 26, 35],
       [47, 38, 47]])

In [79]:
b[(-1, 2, -1, 2), (5, 9, 1, 9)]

array([41, 33, 37, 33])

## Higher dimensions

In [80]:
c = b.reshape(4, 2, 6)
c

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [81]:
c[2, 1, 4]

np.int64(34)

In [82]:
c[2, :, 3]

array([27, 33])

## Ellipsis `...`

In [83]:
c[2, ...]  # matrix 2, all rows, all cosl. => c[2, :, :]

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [84]:
c[2, 1, ...]  # c[2, 1, :]

array([30, 31, 32, 33, 34, 35])

In [85]:
c[2, ..., 3]  # c[2, :, 3]

array([27, 33])

In [86]:
c[..., 3]  # c[:, :, 3]

array([[ 3,  9],
       [15, 21],
       [27, 33],
       [39, 45]])

## Boolean indexing

In [87]:
b = np.arange(48).reshape(4, 12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [88]:
rows_on = np.array([True, False, True, False])
b[rows_on, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [89]:
cols_on = np.array([False, True, False] * 4)
b[:, cols_on]

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22],
       [25, 28, 31, 34],
       [37, 40, 43, 46]])

## `np.ix_`

In [90]:
b[np.ix_(rows_on, cols_on)]  # can't use normal boolean indexing like this, so we use this function

array([[ 1,  4,  7, 10],
       [25, 28, 31, 34]])

In [92]:
b[b % 3 == 1]

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46])

# Iterating

In [93]:
c = np.arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [94]:
for m in c:
    print("Item:")
    print(m)

Item:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Item:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [95]:
for i in range(len(c)):
    print("Item:")
    print(c[i])

Item:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Item:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [97]:
for i in c.flat:
    print("Item:", i)

Item: 0
Item: 1
Item: 2
Item: 3
Item: 4
Item: 5
Item: 6
Item: 7
Item: 8
Item: 9
Item: 10
Item: 11
Item: 12
Item: 13
Item: 14
Item: 15
Item: 16
Item: 17
Item: 18
Item: 19
Item: 20
Item: 21
Item: 22
Item: 23


# Stacking arrays

In [98]:
q1 = np.full((3,4), 1.)
q1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [100]:
q2 = np.full((4,4), 2.)
q2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [101]:
q3 = np.full((3,4), 3.)
q3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

## `vstack` (vertical)

In [103]:
q4 = np.vstack((q1, q2, q3))
q4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [104]:
q4.shape

(10, 4)

## `hstack` (horizontal)



In [105]:
q5 = np.hstack((q1, q3))
q5

array([[1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.]])

In [106]:
q5.shape

(3, 8)

In [107]:
try:
    q5 = np.hstack((q1, q2, q3))
except ValueError as e:
    print(e)

all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4


## `concatenate`

In [108]:
q7 = np.concatenate((q1, q2, q3), axis=0)  # = vstack
q7

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [109]:
q7.shape

(10, 4)

In [110]:
q8 = np.concatenate((q1, q3), axis=1)  # = hstack
q8

array([[1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.]])

## `stack` 

In [111]:
q8 = np.stack((q1, q3))  # must be the same shape. stacks arrays along a new axis
q8

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

# Splitting arrays

In [113]:
r = np.arange(24).reshape(6,4)
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [114]:
r1, r2, r3 = np.vsplit(r, 3)
r1, r2, r3

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [116]:
r4, r5 = np.hsplit(r, 2)
r4, r5

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]]))

# Transposing arrays

In [117]:
t = np.arange(24).reshape(4,2,3)
t

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [118]:
t1 = t.transpose((1, 2, 0))
t1

array([[[ 0,  6, 12, 18],
        [ 1,  7, 13, 19],
        [ 2,  8, 14, 20]],

       [[ 3,  9, 15, 21],
        [ 4, 10, 16, 22],
        [ 5, 11, 17, 23]]])

In [119]:
t1.shape

(2, 3, 4)

In [120]:
t2 = t.transpose()  # = t.transpose((2, 1, 0))
t2

array([[[ 0,  6, 12, 18],
        [ 3,  9, 15, 21]],

       [[ 1,  7, 13, 19],
        [ 4, 10, 16, 22]],

       [[ 2,  8, 14, 20],
        [ 5, 11, 17, 23]]])

In [121]:
t2.shape

(3, 2, 4)

In [122]:
t3 = t.swapaxes(0,1)
t3, t3.shape

(array([[[ 0,  1,  2],
         [ 6,  7,  8],
         [12, 13, 14],
         [18, 19, 20]],
 
        [[ 3,  4,  5],
         [ 9, 10, 11],
         [15, 16, 17],
         [21, 22, 23]]]),
 (2, 4, 3))

# Linear algebra

## Matrix transpose

In [123]:
m1 = np.arange(10).reshape(2,5)
m1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [125]:
m1.T  # = m1.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [126]:
m2 = np.arange(5)
m2

array([0, 1, 2, 3, 4])

In [127]:
m2.T

array([0, 1, 2, 3, 4])

In [131]:
m2r = m2.reshape(1, 5)
m2r, m2r.shape

(array([[0, 1, 2, 3, 4]]), (1, 5))

In [132]:
m2r.T, m2r.T.shape

(array([[0],
        [1],
        [2],
        [3],
        [4]]),
 (5, 1))

## Matrix multiplication

In [133]:
n1 = np.arange(10).reshape(2, 5)
n1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [134]:
n2 = np.arange(15).reshape(5,3)
n2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [135]:
n1.dot(n2)

array([[ 90, 100, 110],
       [240, 275, 310]])

## Matrix inverse and pseudo-inverse

In [136]:
import numpy.linalg as linalg

In [137]:
m3 = np.array([[1,2,3], [5,7,11], [21,29,31]])
m3

array([[ 1,  2,  3],
       [ 5,  7, 11],
       [21, 29, 31]])

In [138]:
linalg.inv(m3)

array([[-2.31818182,  0.56818182,  0.02272727],
       [ 1.72727273, -0.72727273,  0.09090909],
       [-0.04545455,  0.29545455, -0.06818182]])

In [139]:
linalg.pinv(m3)

array([[-2.31818182,  0.56818182,  0.02272727],
       [ 1.72727273, -0.72727273,  0.09090909],
       [-0.04545455,  0.29545455, -0.06818182]])

## Identity matrix

In [140]:
m3.dot(linalg.inv(m3))

array([[ 1.00000000e+00, -1.66533454e-16,  0.00000000e+00],
       [ 6.31439345e-16,  1.00000000e+00, -1.38777878e-16],
       [ 5.21110932e-15, -2.38697950e-15,  1.00000000e+00]])

In [142]:
np.eye(3)  # create identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## QR decomposition

In [144]:
q, r = linalg.qr(m3)
q, r

(array([[-0.04627448,  0.98786672,  0.14824986],
        [-0.23137241,  0.13377362, -0.96362411],
        [-0.97176411, -0.07889213,  0.22237479]]),
 array([[-21.61018278, -29.89331494, -32.80860727],
        [  0.        ,   0.62427688,   1.9894538 ],
        [  0.        ,   0.        ,  -3.26149699]]))

In [145]:
q.dot(r)  # = m3

array([[ 1.,  2.,  3.],
       [ 5.,  7., 11.],
       [21., 29., 31.]])

## Determinant

In [147]:
linalg.det(m3)

np.float64(43.99999999999997)

## Eigenvalues and eigenvectors

In [149]:
eigenvalues, eigenvectors = linalg.eig(m3)
eigenvalues, eigenvectors

(array([42.26600592, -0.35798416, -2.90802176]),
 array([[-0.08381182, -0.76283526, -0.18913107],
        [-0.3075286 ,  0.64133975, -0.6853186 ],
        [-0.94784057, -0.08225377,  0.70325518]]))

# Vectoriazation
we want a 768x1024 array based on the formula $sin(xy/40.5)$

In [150]:
# bad slow code
import math 

data = np.empty((768, 1024))
for y in range(768):
    for x in range(1024):
        data[y,x] = math.sin(x * y / 40.5)

In [153]:
x_coords = np.arange(0, 1024)  # [0, 1, 2, ..., 1023]
y_coords = np.arange(0, 768)  # [0, 1, 2, ..., 767]
X, Y = np.meshgrid(x_coords, y_coords)
X, Y

(array([[   0,    1,    2, ..., 1021, 1022, 1023],
        [   0,    1,    2, ..., 1021, 1022, 1023],
        [   0,    1,    2, ..., 1021, 1022, 1023],
        ...,
        [   0,    1,    2, ..., 1021, 1022, 1023],
        [   0,    1,    2, ..., 1021, 1022, 1023],
        [   0,    1,    2, ..., 1021, 1022, 1023]], shape=(768, 1024)),
 array([[  0,   0,   0, ...,   0,   0,   0],
        [  1,   1,   1, ...,   1,   1,   1],
        [  2,   2,   2, ...,   2,   2,   2],
        ...,
        [765, 765, 765, ..., 765, 765, 765],
        [766, 766, 766, ..., 766, 766, 766],
        [767, 767, 767, ..., 767, 767, 767]], shape=(768, 1024)))

In [155]:
data = np.sin(X * Y / 40.5)
data

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.02468885, 0.04936265, ..., 0.07705885, 0.1016508 ,
        0.12618078],
       [0.        , 0.04936265, 0.09860494, ..., 0.15365943, 0.20224852,
        0.25034449],
       ...,
       [0.        , 0.03932283, 0.07858482, ..., 0.6301488 , 0.59912825,
        0.56718092],
       [0.        , 0.06398059, 0.12769901, ..., 0.56844086, 0.51463783,
        0.45872596],
       [0.        , 0.08859936, 0.17650185, ..., 0.50335246, 0.42481591,
        0.34293805]], shape=(768, 1024))

# Saving and loading

In [156]:
a = np.random.rand(2, 3)
a

array([[0.59877595, 0.46840736, 0.94715257],
       [0.90931668, 0.63947121, 0.65978837]])

In [157]:
np.save("my_array", a)  # binary format

In [158]:
with open("my_array.npy", "rb") as f:
    content = f.read()

content

b"\x93NUMPY\x01\x00v\x00{'descr': '<f8', 'fortran_order': False, 'shape': (2, 3), }                                                          \n\xa3\xf0\xb00,)\xe3?\x08F\x0e\xe2b\xfa\xdd?\xf8\xcd\x9c\xe8\x12O\xee?\x92\xc2\xdbL\x1f\x19\xed?E\xf9\x06U\x8cv\xe4?\x11\xbfE~\xfc\x1c\xe5?"

In [159]:
a_loaded = np.load("my_array.npy")
a_loaded

array([[0.59877595, 0.46840736, 0.94715257],
       [0.90931668, 0.63947121, 0.65978837]])

## Text format

In [160]:
np.savetxt("my_array.csv", a)

In [161]:
with open("my_array.csv", "rt") as f:
    print(f.read())

5.987759543418359476e-01 4.684073646140807234e-01 9.471525710309256496e-01
9.093166829244003768e-01 6.394712124527265340e-01 6.597883669146274999e-01



## Zipped `.npz` format

In [163]:
b = np.arange(24, dtype=np.uint8).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=uint8)

In [164]:
np.savez("my_arrays", my_a=a, my_b=b)

In [165]:
with open("my_arrays.npz", "rb") as f:
    content = f.read()

repr(content)[:180] + "[...]"

'b"PK\\x03\\x04-\\x00\\x00\\x00\\x00\\x00\\x00\\x00!\\x009L\\xc2\\xa7\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\x08\\x00\\x14\\x00my_a.npy\\x01\\x00\\x10\\x00\\xb0\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\xb0\\x00\\x00\\x00\\x00[...]'

In [166]:
my_arrays = np.load("my_arrays.npz")
my_arrays

NpzFile 'my_arrays.npz' with keys: my_a, my_b

In [168]:
my_arrays.keys()

KeysView(NpzFile 'my_arrays.npz' with keys: my_a, my_b)

In [169]:
my_arrays["my_a"]

array([[0.59877595, 0.46840736, 0.94715257],
       [0.90931668, 0.63947121, 0.65978837]])